version: '3.8'

services:
  app:
    build: .
    container_name: go-fiber-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/tmp
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=yourpass
      - DB_NAME=bookdb
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpass
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
    driver: bridge
